### ISSUE TITLE
updateable = false 

### ISSUE THREAD

**Issue by tngus3722** [tngus3722/WHOPUPPY_BACKEND#1]
![image](https://user-images.githubusercontent.com/32263898/129327725-e62cbbf3-6741-434e-9cc7-60c5a4a437af.png)

UpdateTimestamp 에 updatble = false가 되어있다면 update 쿼리시 시간이 수정안되지 않나요?

**Comment by tngus3722** [comment]
@xhdtn8070  @xhddlf8070

**Comment by xhdtn8070** [comment]
![image](https://user-images.githubusercontent.com/19249550/129333085-b57f1fa9-c234-49ef-b2c4-34a771f50617.png)
이 사진을 보면 ddl에 update 옵션을 넣은것이 보입니다.
저 컬럼의 updatable을 false로 한다는 것은 해당 컬럼의 자동 수정을
JPA에서 컨트롤 하지 않고 DB에 자체적으로 맞긴다는 의미입니다.
지적한대로 위에 UpdateTimestamp를 지워도 되는 상황이지만 DBMS 상황에 따라 저것을 true, false하는 것으로 제어하도록 해놨습니다.
기존 DDL 보면 update로 안되있고해서요

**Comment by tngus3722** [comment]
꺄올 당신은 다 계획이 있었군요. ?!
